server:
  port: 8081


# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://121.43.40.44:3306/flash_sale?serverTimezone=Asia/Shanghai
    username: root
    password: root1234
    driver: com.mysql.Driver